name: github-project-issue-to-sheets

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [ labeled ]

jobs:
    github-project-issue-to-sheets:
        if: ${{ github.event.label.name == 'test' }}
        runs-on: ubuntu-latest
        name: github-project-issue-to-sheets
        steps:
        - name: github-project-issue-to-sheets
          id: github-project-issue-to-sheets
          uses: ViRGiL175/github-project-issue-to-sheets@dev
          with:
            google-api-service-account-credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_DATA }}
            document-id: '1b0UuGS_HXTGv-BE9dcB_58gZvo5fttyKgle0s4DmRNI'
            sheet-name: 'GitHub Issues'
